[model]
names = ["Bell-LaPadula"]

[levels]
order = ["Unclassified", "Confidential", "Secret", "Top Secret"]

[categories]
sets = ["Nuclear", "Crypto", "Personnel"]

[objects]
"stdin" = { level = "Unclassified", categories = [] }
"stdout" = { level = "Unclassified", categories = [] }
"public_network" = { level = "Unclassified", categories = [] }
"public_status.txt" = { level = "Unclassified", categories = [] }
"employee_directory.csv" = { level = "Confidential", categories = ["Personnel"] }
"crypto_keys.txt" = { level = "Top Secret", categories = ["Crypto"] }
"reactor_report.txt" = { level = "Secret", categories = ["Nuclear"] }
"joint_incident_report.txt" = { level = "Top Secret", categories = ["Crypto", "Nuclear"] }
"admin_audit.log" = { level = "Secret", categories = ["Personnel"] }

[effects.SOURCE]
reads = "crypto_keys.txt"
returns = true

[effects.SINK]
writes = "public_network"
reads_from_args = [0]

[effects.scanf]
reads = "stdin"
writes_to_args = [1]

[effects.printf]
writes = "stdout"
reads_from_args = [1, 2]

[effects.SOURCE_PUBLIC_NETWORK]
reads = "public_network"
returns = true

[effects.SOURCE_PERSONNEL_DB]
reads = "employee_directory.csv"
returns = true

[effects.SOURCE_CRYPTO_KEYSTORE]
reads = "crypto_keys.txt"
returns = true

[effects.SOURCE_REACTOR_REPORT]
reads = "reactor_report.txt"
returns = true

[effects.SINK_PUBLIC_NETWORK]
writes = "public_network"
reads_from_args = [0]

[effects.SINK_PERSONNEL_LOG]
writes = "employee_directory.csv"
reads_from_args = [0]

[effects.SINK_CRYPTO_AUDIT]
writes = "admin_audit.log"
reads_from_args = [0]
