[model]
names = ["Bell-LaPadula", "Biba"]

[confidentiality_levels]
order = ["Unclassified", "Confidential", "Secret", "Top Secret"]

[integrity_levels]
order = ["Untrusted", "Low Integrity", "Medium Integrity", "High Integrity", "Trusted"]

[confidentiality_categories]
sets = ["Nuclear", "Crypto", "Personnel"]

[integrity_categories]
sets = ["Sensor", "Audit", "Control", "Config"]

[objects."stdin"]
classification = "Unclassified"
integrity = "Untrusted"
confidentiality_categories = []
integrity_categories = []

[objects."stdout"]
classification = "Unclassified"
integrity = "Untrusted"
confidentiality_categories = []
integrity_categories = []

[objects."public_network"]
classification = "Unclassified"
integrity = "Low Integrity"
confidentiality_categories = []
integrity_categories = []

[objects."employee_directory.csv"]
classification = "Confidential"
integrity = "Medium Integrity"
confidentiality_categories = ["Personnel"]
integrity_categories = []

[objects."crypto_keys.txt"]
classification = "Top Secret"
integrity = "Trusted"
confidentiality_categories = ["Crypto"]
integrity_categories = ["Config"]

[objects."reactor_report.txt"]
classification = "Secret"
integrity = "High Integrity"
confidentiality_categories = ["Nuclear"]
integrity_categories = ["Sensor"]

[objects."joint_incident_report.txt"]
classification = "Top Secret"
integrity = "High Integrity"
confidentiality_categories = ["Crypto", "Nuclear"]
integrity_categories = ["Audit"]

[objects."operator_command.log"]
classification = "Secret"
integrity = "Medium Integrity"
confidentiality_categories = []
integrity_categories = ["Control", "Audit"]

[objects."public_upload"]
classification = "Unclassified"
integrity = "Untrusted"
confidentiality_categories = []
integrity_categories = []

[objects."system_config.toml"]
classification = "Secret"
integrity = "Trusted"
confidentiality_categories = []
integrity_categories = ["Config"]

[effects.SOURCE]
reads = "crypto_keys.txt"
returns = true

[effects.SINK]
writes = "public_network"
reads_from_args = [0]

[effects.scanf]
reads = "stdin"
writes_to_args = [1]

[effects.printf]
writes = "stdout"
reads_from_args = [1, 2]

[effects.SOURCE_PUBLIC_NETWORK]
reads = "public_network"
returns = true

[effects.SOURCE_PUBLIC_UPLOAD]
reads = "public_upload"
returns = true

[effects.SOURCE_PERSONNEL_DB]
reads = "employee_directory.csv"
returns = true

[effects.SOURCE_CRYPTO_KEYSTORE]
reads = "crypto_keys.txt"
returns = true

[effects.SOURCE_REACTOR_REPORT]
reads = "reactor_report.txt"
returns = true

[effects.SINK_PUBLIC_NETWORK]
writes = "public_network"
reads_from_args = [0]

[effects.SINK_AUDIT_LOG]
writes = "operator_command.log"
reads_from_args = [0]

[effects.SINK_SYSTEM_CONFIG]
writes = "system_config.toml"
reads_from_args = [0]
